### ISSUE TITLE
It doesn't work with Crystal 0.24.1 anymore

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang-tools/sublime-crystal#32]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "crystal_format in /home/faust/.config/sublime-text-3/Installed Packages/sublime-crystal.sublime-package", line 52, in run
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
... and so on
```

**Comment by vladfaust** [comment]
Any updates?

**Comment by vladfaust** [comment]
Bump, this is critical for me, anyone could reproduce it?

**Comment by vladfaust** [comment]
Really

**Comment by faustinoaq** [comment]
@vladfaust Sorry for the late response, I'm organizing the issues and PRs to track them easily :sweat_smile: 

Check https://github.com/orgs/crystal-lang-tools/projects/1?fullscreen=true :wink:

**Comment by vladfaust** [comment]
@fgimian I would be happy if you could help me with that :cry:

**Comment by fgimian** [comment]
Yep, I can reproduce it as follows.

Ensure that `auto_format` is enabled (this is enabled by default in the Crystal Sublime extension).  Then once saving the file:

```
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/fots/Library/Application Support/Sublime Text 3/Installed Packages/Crystal.sublime-package/crystal_format.py", line 52, in run
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```

I'm sure we can fix this quite easily.  I personally don't like `auto_format` to be enabled, especially by default, and thus I disable it myself so I've never noticed this problem.

If I get a little spare time, I'll try to assist with a fix for this extension.

Cheers
Fotis

**Comment by fgimian** [comment]
The problem is simply that there's no exception handling in https://github.com/crystal-lang-tools/sublime-crystal/blob/master/crystal_format.py if things go wrong.

Cheers
Fotis
